name: CI - gridcapa-core-cc

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        if: matrix.os == 'ubuntu-latest'
        run: mvn --batch-mode -Pcoverage install

      - name: Build with Maven
        if: matrix.os != 'ubuntu-latest'
        run: mvn --batch-mode install